### ISSUE TITLE
Does it have echo cancellation?

### ISSUE THREAD

**Issue by desertkun** [Epicguru/VoiceChat#1]
I am currently looking a voice chat solution for my game and your project is 100% hit.
However, I consider echo issue might be disturbing to the point no one would ever use that chat.

So, does it have echo cancellation in some kind?

**Comment by Epicguru** [comment]
Sorry, this is super late and probably irrelevant to you by this point, but the answer is yes, it does. Rather than echo cancellation there is ‘echo prevention’ meaning that the audio data is not sent to the client that recorded it. The reason why you hear an echo in the example project is because I set it up intentionally this way, to ensure that the audio was being sent.

If you are still interested in this project, I am going to update it soon to fix some core issues such as lack of optimisation and flexibility. If you have used a different solution or have moved on, I’m glad that you took an interest in this anyway!
Have a good day.
